import { describe, it, expect } from 'vitest';
import { COPILOT_TOOLS, TOOL_NAMES, renderToolsSection, renderToolsGeneratedFile } from './copilotTools';
import { normalizeActions } from './copilot';
import { proposalGaps } from './proposalGaps';
import { buildProposalSurface } from './copilotSurfaces';
import { applySurfaceMessages } from './a2ui';
import type { EventSnapshot } from './eventSnapshot';
import { FRAME_CREDIT_COST, GENERATE_3D_CREDIT_COST } from './studio/sceneDirector';

// The registry examples reference one challenge id and one experience id —
// the same fixture shape copilot.test.ts / copilotSurfaces.test.ts use.
const snapshot = {
  eventUuid: 'u-1', slug: 'e', name: 'E', status: 'draft', planTier: 'free', eventType: 'party',
  failed: false, postCount: 0, showChallenges: true,
  challenges: [{ id: 'ch-1', title: 'C', emoji: '⭐', points: 10, active: true }],
  experiences: [{ id: 'exp-1', name: 'Frame', kind: 'border', published: true }],
  cards: [],
} satisfies EventSnapshot;

describe('COPILOT_TOOLS — every entry round-trips through the client gates', () => {
  for (const name of TOOL_NAMES) {
    const spec = COPILOT_TOOLS[name];

    it(`${name}: example survives normalizeActions as exactly one ${name}`, () => {
      const out = normalizeActions([{ tool: name, ...spec.example }], snapshot);
      expect(out).toHaveLength(1);
      expect(out[0].tool).toBe(name);
    });

    it(`${name}: example leaves proposalGaps empty`, () => {
      expect(proposalGaps(name, spec.example)).toEqual([]);
    });

    it(`${name}: buildProposalSurface is non-empty iff confirm`, () => {
      const [action] = normalizeActions([{ tool: name, ...spec.example }], snapshot);
      const msgs = buildProposalSurface(action, 's');
      expect(msgs.length > 0).toBe(spec.confirm);
      if (spec.confirm) {
        // and the heading is the registry label
        const s = applySurfaceMessages({}, msgs).s;
        expect(String(s.components.heading.text)).toContain(spec.label);
      }
    });

    it(`${name}: name field matches its key; readOnly tools never confirm`, () => {
      expect(spec.name).toBe(name);
      if (spec.readOnly) expect(spec.confirm).toBe(false);
    });
  }

  it('the two handoff tools are present, confirmed, free', () => {
    expect(COPILOT_TOOLS.open_scene_director).toMatchObject({ confirm: true, readOnly: false, costNote: null });
    expect(COPILOT_TOOLS.contact_support).toMatchObject({ confirm: true, readOnly: false, costNote: null });
    expect(COPILOT_TOOLS.open_scene_director.whenNotToUse).toMatch(/single frame, filter or prop/i);
  });

  it('cost notes derive their numbers from sceneDirector, never a literal', () => {
    expect(COPILOT_TOOLS.generate_frame.costNote).toContain(`${FRAME_CREDIT_COST} credit`);
    expect(COPILOT_TOOLS.add_head_piece.costNote).toContain(`~${GENERATE_3D_CREDIT_COST + FRAME_CREDIT_COST} credits`);
  });
});

describe('renderToolsSection', () => {
  const section = renderToolsSection();
  const lines = section.split('\n');

  it('starts with the "# Tools" heading', () => {
    expect(lines[0]).toBe('# Tools');
  });

  it('names every tool exactly once as a line start, with every parameter', () => {
    for (const name of TOOL_NAMES) {
      const starts = lines.filter((l) => l.startsWith(`- ${name} `));
      expect(starts, name).toHaveLength(1);
      for (const param of Object.keys(COPILOT_TOOLS[name].params)) {
        expect(section).toContain(`  · ${param} (`);
      }
    }
  });

  it('keeps every line at or under 400 characters (one explicit action per line)', () => {
    for (const l of lines) expect(l.length, l).toBeLessThanOrEqual(400);
  });

  it('marks optional params with ? on the tool line and "optional" on the param line', () => {
    expect(section).toContain('- add_challenge { title, emoji?, points?, description?, validationPrompt? }');
    expect(section).toContain('  · emoji (string, optional):');
    expect(section).toContain('- go_live {} —');
    expect(section).toContain('Not for: a 3D model or prop request');
  });

  it('renders enum params as their alternatives', () => {
    expect(section).toContain('  · source (builtin | generate, required):');
  });
});

describe('renderToolsGeneratedFile', () => {
  it('is a @generated module exporting TOOLS_SECTION and TOOL_NAMES', () => {
    const file = renderToolsGeneratedFile();
    expect(file.startsWith('// @generated by scripts/gen-agent-tools.ts from src/lib/copilotTools.ts — DO NOT EDIT; run npm run gen:agent-tools\n')).toBe(true);
    expect(file).toContain(`export const TOOLS_SECTION: string = ${JSON.stringify(renderToolsSection())};`);
    expect(file).toContain(`export const TOOL_NAMES = ${JSON.stringify([...TOOL_NAMES])} as const;`);
    expect(file.endsWith('\n')).toBe(true);
  });
});
