/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 *
 * The Platform Guide — a hand-written digest of how Beamwall works, sent as
 * grounding for the copilot's help mode (same "client's live copy wins"
 * pattern as the template catalog; the edge fn caps it at 12k chars and
 * falls back to a one-liner). Keep it terse, factual, and current — this IS
 * what the agent knows about the product. Update it when surfaces change.
 */
export const PLATFORM_GUIDE = `
BEAMWALL — self-serve AR photo-booth + live photo-wall + keepsake-card platform for events (weddings, galas, birthdays, corporate, parties). Everything runs in the browser; guests never install an app.

GUEST EXPERIENCE (per event, at /e/<slug>):
- /welcome — landing page explaining the event's features, one tap into each; best target for printed signage QRs.
- /booth — AR photo booth: live face-tracked 3D pieces (crowns, glasses…), frames, shader effects, photo + video capture, countdown timer, front/back camera. Captures beam to the wall.
- /wall — the live photo wall (project it at the venue); realtime, with optional QR overlay and challenge leaderboard.
- /upload — guests send photos from their camera roll to the wall.
- /challenges — photo missions (each has a title, emoji, points); completing one tags the capture and scores the leaderboard. Hosts toggle the feature per event.
- Moderation: hosts approve/hide posts in the studio Wall tab; day-of staff can use a manager link (token) at /m/<slug>.

HOST STUDIO (/host/events/<id>, tabs):
- Dashboard: go-live checklist (name, look, frames, test photo), live stats, Go-live button (event starts as draft; guests join once live).
- Experiences (library): every frame/filter/3D piece; publish/unpublish; set booth default.
- Studio: one unified editor for every experience — and experiences are now mixed scenes: a frame, any number of stickers, 3D head-anchored props, and one shader filter can all live together in a single draft (no more separate 2D/3D/filter experience types). Browse or drag built-in art, uploads, and head pieces onto the canvas; upload art or AI-generate frames/stickers (first 3 AI images per event are free, then 1 credit each) — AI-generated frames come back transparent (green-screen keyed server-side, not just alpha-cropped), so they layer cleanly over guest photos. 3D props are AI-generated by a Gemini → Meshy pipeline (Gemini designs the concept image, Meshy turns it into a textured GLB) and are occluded by the real head, with a per-event "head size" slider to match real faces. Preview shows the composited result exactly as guests capture it, all sharing one camera. Naming: click the experience name centered in the header to rename inline; Save persists the whole composite (frame + stickers + 3D + filter) as one experience.
- Director: a docked AI panel inside the Studio (not a popup) — describe a look in one prompt and matching pieces (frame, filter, 3D piece) stream in one at a time into the draft that's already open, so you accept or skip each piece without leaving the canvas. Save any finished draft as a reusable template ("Save as template") and start new experiences from one via the Assets dock's Mine tab (Templates). This is the studio's own AI surface — the floating copilot deliberately stays out of the Studio route so there's exactly one assistant per surface.
- Assets: every file uploaded to the event's asset bucket (browse, copy URL, delete).
- Wall: moderation + wall settings (QR, leaderboard, challenges toggle).
- Challenges: create/edit/delete photo missions (title, emoji, points, active).
- Cards: greeting cards / video guestbook — create a card, share its contribution link (/c/<publicId>/contribute?t=<token>) so anyone can add photos/videos/notes; publish makes the card viewable at /c/<publicId>; publishing/email requires a premium+ event (or org Pro subscription); Deluxe adds a rendered MP4 keepsake film (30 credits).
- Share: QR kit for every guest surface + print signage mode.
- Branding: theme colours, background, fonts, copy. Settings: landing route, defaults. Manager access: mint day-of staff links.

CREATING EVENTS:
- /host/new — the Event Concierge: describe the event in chat and the AI designs it (name, style template, accent colour, date, link, remote mode) with a live preview card; or use the manual 3-step wizard. On success, the AI Frame Studio designs a signature 9:16 frame, publishes it and sets it as the booth default (drag to position, size slider).
- /host/concierge — the Concierge workspace: every event as a card (rename inline, go live/end, copy link, open studio) beside this chat; pick an event and manage it in plain words. Ask for a "challenge pack" to get a themed set of 3-6 challenges added in one confirm.
- Remote/virtual celebrations: guests contribute to a greeting card from anywhere; the card can be pinned as the event landing.

PLANS & CREDITS:
- Tiers per event: free (25 posts, photo only, watermark, 7-day retention) → essentials (500 posts, video, no watermark, AI studio) → premium (unlimited posts, cards) → deluxe (premium render/keepsake film). An org-level Pro subscription raises every event to premium-level.
- Credits: AI generation currency (1 credit ≈ one AI image; 3D and film cost more). Bought in packs; first 3 images per event are free. Billing lives at /host/billing.

COMMON HOW-TOS:
- Show someone what Beamwall does without an account: the home page (/) has a live no-sign-in demo booth — real AR camera, frames, effects and a mini live wall.
- Go live: finish the Dashboard checklist → Go live button. Share: Share tab → print signage (point signage at /welcome).
- Change the booth's default frame: Experiences → publish the frame → set as default (or let the Frame Studio do it at create time).
- Design a whole coordinated look fast: Studio → Director → describe the vibe → accept the frame, filter, and 3D piece it streams in.
- Make a 3D prop sit right on real faces: Studio → nudge the "Head size" slider (Properties) up if props look small in Preview.
- Reuse a look on a new experience: Studio → open a saved template from the Assets dock's Mine tab, or save the current draft as one ("Save as template").
- Add a challenge: Challenges tab → New challenge (or ask the copilot).
- Make a greeting card: Cards tab → create card → copy the contribution link (or ask the copilot). Publish when ready to share the viewer link.
- Day-of staff: Manager access tab → create token → share /m/<slug> link.
`.trim();
